name := "rich-whiley-sandpit"
organization := "nz.rd.whiley"
scalaVersion := "2.11.8"
libraryDependencies += "com.assembla.scala-incubator" %% "graph-core" % "1.11.0"
libraryDependencies += "org.scalatest" %% "scalatest" % "2.2.6" % "test"
